### ISSUE TITLE
trace_printk() use

### ISSUE THREAD

**Issue by JaredTamana** [quantify-nfc/Wear24-NFC-Kernel#20] opened 2019-03-27 00:39 UTC
[    0.087237] **********************************************************
[    0.087255] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
[    0.087265] **                                                      **
[    0.087275] ** trace_printk() being used. Allocating extra memory.  **
[    0.087284] **                                                      **
[    0.087293] ** This means that this is a DEBUG kernel and it is     **
[    0.087302] ** unsafe for produciton use.                           **
[    0.087311] **                                                      **
[    0.087321] ** If you see this message and you are not debugging    **
[    0.087330] ** the kernel, report this immediately to your vendor!  **
[    0.087339] **                                                      **
[    0.087348] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
[    0.087357] **********************************************************
- [x] Find the uses of trace_prink() in kernel code
- [x] Remove them
- [ ] Check the issue no longer exists
- [ ] Push to release!

**Comment by davwheat** [comment] 2019-03-27 00:40
I have tried to fix this before but I must have missed some printk statements.

I'll get on it tomorrow.

**Comment by davwheat** [comment] 2019-03-28 20:28
50f4a0f should fix the issue.

Needs testing!

**Comment by davwheat** [comment] 2019-05-03 12:06
Duplicate of #13

**Closed as completed by davwheat** 2019-05-03 12:06 UTC
Labels: Low, Needs testing

**Comment by JaredTamana** [comment] 2019-05-03 13:22
Is trace_printk() removed entirely now? I did not notice #13 and the fact that you commented that some instances will not be removed. 

We should probably bring back the `wontfix` tag.

**Comment by davwheat** [comment] 2019-05-03 13:34
Some weren't going to be removed whilst debugging because that's what
they're used for. Not your fault, I closed the issue and forgot about it
too. Still need to see if the kernel complains about printk; I haven't
tested it yet.
